version: '3.8'

networks:
  kafka-network:
    driver: bridge

services:

  kafka-service:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    networks:
      - kafka-network
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-service:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-service:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    
    healthcheck:
      test: ["CMD", "/usr/local/bin/kafka-broker-check"]
      interval: 30s
      timeout: 10s
      retries: 3

  notification-app:
    image: notification-app:latest
    build:
      context: .
    container_name: notification-app
    ports:
      - "8081:8081"
    environment:
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CONSUMER_GROUP=notification-app
    depends_on:
      - kafka-service
    networks:
      - kafka-network
    restart: unless-stopped

volumes:
  kafka_data:
    driver: local