apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      # initContainers:
      #   - name: create-topic
      #     image: bitnami/kafka:latest
      #     command:
      #       - sh
      #       - -c
      #       - |
      #         /opt/bitnami/kafka/bin/kafka-topics.sh \
      #         --create \
      #         --topic notifications \
      #         --bootstrap-server kafa-service:9092 \
      #         --partitions 1 \
      #         --replication-factor 1
      #     envFrom:
      #       - configMapRef:
      #           name: kafka-config
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          ports:
            - containerPort: 9092
          envFrom:
            - configMapRef:
                name: kafka-config
          volumeMounts:
            - mountPath: /bitnami/kafka
              name: kafka-storage
          livenessProbe: null
          readinessProbe: null
          resources:
            limits:
              cpu: "1000m"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"
          
      volumes:
        - name: kafka-storage
          persistentVolumeClaim:
            claimName: kafka-pvc